apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: tcp-ip
  labels:
    app: streamlit
spec:
  ports:
    - name: dashboard
      port: 8501
      targetPort: 8501
  selector:
    app: streamlit
