apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: tcp-ip
spec:
  ports:
    - name: dashboard
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
