apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-log
  namespace: tcp-ip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
