apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emqx
  name: emqx
  namespace: tcp-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        server-default: "true"
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx:latest
          securityContext:
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 18083
              hostPort: 18083
              protocol: TCP
            - containerPort: 1883
              hostPort: 1883
              protocol: TCP
            - containerPort: 8883
              hostPort: 8883
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/emqx/data
              name: emqx-data
            - mountPath: /opt/emqx/log
              name: emqx-log
      restartPolicy: Always
      volumes:
        - name: emqx-data
          persistentVolumeClaim:
            claimName: emqx-data
        - name: emqx-log
          persistentVolumeClaim:
            claimName: emqx-log