apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: tcp-ip
  labels:
    app: emqx
spec:
  ports:
    - name: dashboard
      port: 18083
      targetPort: 18083
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtts
      port: 8883
      targetPort: 8883
  selector:
    app: emqx