apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-tools
  labels:
    app: jenkins
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: jnlp
    port: 5000
    targetPort: 5000
  selector:
    app: jenkins
  type: LoadBalancer
