apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tcp-ip
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: dashboard
      port: 3306
      targetPort: 3306
